title: 'dieantu.github.io'
description: "A jekyll theme inspired by linux consoles for hackers, developers and script kiddies."
url: "https://dieantu.com"

header_pages:
  - index.md
  - privacy-links.md
  - contact.md

style: dark

footer: '-contact(at)dieantu.com- 887F 98F9 3318 C1D4 7037 E0BF C8EC E040 E788 224F'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
